allowBuilds:
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@oh-my-pi/omp-stats@18.1.6'
  - '@oh-my-pi/omptype@18.1.6'
  - '@oh-my-pi/pi-agent-core@18.1.6'
  - '@oh-my-pi/pi-ai@18.1.6'
  - '@oh-my-pi/pi-catalog@18.1.6'
  - '@oh-my-pi/pi-coding-agent@18.1.6'
  - '@oh-my-pi/pi-mnemopi@18.1.6'
  - '@oh-my-pi/pi-natives-darwin-arm64@18.1.6'
  - '@oh-my-pi/pi-natives-darwin-x64@18.1.6'
  - '@oh-my-pi/pi-natives-linux-arm64@18.1.6'
  - '@oh-my-pi/pi-natives-linux-x64@18.1.6'
  - '@oh-my-pi/pi-natives-win32-x64@18.1.6'
  - '@oh-my-pi/pi-natives@18.1.6'
  - '@oh-my-pi/pi-tui@18.1.6'
  - '@oh-my-pi/pi-utils@18.1.6'
  - '@oh-my-pi/pi-wire@18.1.6'
  - '@oh-my-pi/snapcompact@18.1.6'
